// Code generated by hertz generator.

package xzdp

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usermethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shop_typeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shoplistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
