// Code generated by hertz generator.

package main

import (
	"context"
	"xzdp/biz/dal/mysql"
	"xzdp/biz/dal/redis"
	"xzdp/biz/middleware/interceptor"
	"xzdp/conf"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts(conf.GetConf().Hertz.Address))
	h.Use(interceptor.CheckToken)

	excludedPaths := map[string]bool{
		"/shop":       true,
		"/voucher":    true,
		"/shop-type":  true,
		"/upload":     true,
		"/blog/hot":   true,
		"/user/code":  true,
		"/user/login": true,
	}
	h.Use(func(ctx context.Context, c *app.RequestContext) {
		if _, ok := excludedPaths[string(c.Request.Path())]; !ok {
			interceptor.LoginInterceptor(ctx, c)
		}
	})

	mysql.Init()
	redis.Init()

	register(h)
	h.Spin()
}
