// Code generated by hertz generator.

package follow

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _follow0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _isfollowedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commonfollowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _isfollowed0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _notMw() []app.HandlerFunc {
	// your code...
	return nil
}
