// Code generated by hertz generator.

package blog_comment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}
