// Code generated by hertz generator.

package blog

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ofMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogofmeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlikesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollowblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _of0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blogofmeMw() []app.HandlerFunc {
	// your code...
	return nil
}
