// Code generated by hertz generator.

package blog

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotblogMw() []app.HandlerFunc {
	// your code...
	return nil
}
