// Code generated by hertz generator.

package shop

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shop_typeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shoplistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shopMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ofMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shopoftypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shopinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _typeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shopoftypegeoMw() []app.HandlerFunc {
	// your code...
	return nil
}
