// Code generated by hertz generator.

package shop

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shop_typeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shoplistMw() []app.HandlerFunc {
	// your code...
	return nil
}
