// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	blog "xzdp/biz/router/blog"
	blog_comment "xzdp/biz/router/blog_comment"
	follow "xzdp/biz/router/follow"
	image "xzdp/biz/router/image"
	message "xzdp/biz/router/message"
	shop "xzdp/biz/router/shop"
	user "xzdp/biz/router/user"
	voucher "xzdp/biz/router/voucher"
	xzdp "xzdp/biz/router/xzdp"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	voucher.Register(r)

	message.Register(r)

	blog_comment.Register(r)

	image.Register(r)

	follow.Register(r)

	shop.Register(r)

	user.Register(r)

	blog.Register(r)

	xzdp.Register(r)
}
