// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	blog "xzdp/biz/router/blog"
	follow "xzdp/biz/router/follow"
	shop "xzdp/biz/router/shop"
	user "xzdp/biz/router/user"
	xzdp "xzdp/biz/router/xzdp"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	follow.Register(r)

	shop.Register(r)

	user.Register(r)

	blog.Register(r)

	xzdp.Register(r)
}
